name: Deploy

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    container: pandoc/latex

    steps:
      - uses: actions/checkout@v3

      - name: Install mustache (to update the date)

        run: apk add ruby && gem install mustache

      - name: creates output

        run: sh ./build.sh

      - name: Pushes to another repository

        id: push_directory

        uses: cpina/github-action-push-to-another-repository@dev

        env:
          API_TOKEN_GITHUB: ${{ secrets.FORK_AUTO_TOKEN }}

        with:
          source-directory: 'output'

          destination-github-username: jamooooong

          destination-repository-name: 47th-web-vercel

          user-email: ${{ secrets.EMAIL }}

          commit-message: ${{ github.event.commits[0].message }}

          target-branch: main

      - name: Test get variable exported by push-to-another-repository

        run: echo $DESTINATION_CLONED_DIRECTORY
