name: Sync Fork

on:
  push:
    branches: ['dev'] # 원본 저장소의 dev 브랜치에 푸시가 있을 때 실행
  schedule:
    - cron: '0 * * * *' # 매번실행 (선택사항)

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 모든 히스토리를 가져옵니다

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add remote for fork
        run: |
          git remote add fork https://${{ secrets.FORK_AUTO_TOKEN }}@github.com/jamooooong/47th-web-vercel.git

      - name: Fetch and merge from original repo
        run: |
          git fetch origin
          git checkout dev
          git merge origin/dev

      - name: Push to fork
        run: |
          git push fork dev:main --force
